
/* 1 "LANCEV2" */
/* $
     IR file generated by LANCE V2.0 (stcleanup) on
     Sunday, Jun 21, 2020 at 09:49:34
$ */

int print_digits(int );
int main();

static char *lance_static_t3 = "%d ";

static char *lance_static_t8 = "%d\n";

int print_digits(int n_2)
{
 int temp_4;
 int t2;
 int t4;
 int t5;


 /* 4 "/home/anushkini/Desktop/PD/plagtool/Test_lance/pd_2.c" */
 /* $ temp = n % 10;$ */

	t2 = n_2 % 10;
	temp_4 = t2;

 /* 5 "/home/anushkini/Desktop/PD/plagtool/Test_lance/pd_2.c" */
 /* $ printf("%d ",temp);$ */

	t4 = printf(lance_static_t3,temp_4);

 /* 6 "/home/anushkini/Desktop/PD/plagtool/Test_lance/pd_2.c" */
 /* $ n = n / 10;$ */

	t5 = n_2 / 10;
	n_2 = t5;

 /* 3 "/home/anushkini/Desktop/PD/plagtool/Test_lance/pd_2.c" */
 /* $ while(n >= 10) {$ */

 LL1:

 /* 8 "/home/anushkini/Desktop/PD/plagtool/Test_lance/pd_2.c" */
 /* $ return temp;$ */

	return temp_4;

}

int main()
{
 int n_11;
 int t7;
 int l_12;
 int t9;
 int t17;


 /* 15 "/home/anushkini/Desktop/PD/plagtool/Test_lance/pd_2.c" */
 /* $ int n = 12345;$ */

	n_11 = 12345;

 /* 16 "/home/anushkini/Desktop/PD/plagtool/Test_lance/pd_2.c" */
 /* $ int l = print_digits(n);$ */

	t7 = print_digits(n_11);
	l_12 = t7;

 /* 17 "/home/anushkini/Desktop/PD/plagtool/Test_lance/pd_2.c" */
 /* $ printf("%d\n",l);$ */

	t9 = printf(lance_static_t8,l_12);

 /* 19 "/home/anushkini/Desktop/PD/plagtool/Test_lance/pd_2.c" */
 /* $ for(i = 0; i < 10; i++) {$ */

	if (t17) goto LL4;

 LL4:

 /* 0 "???" */
 /* $ ???$ */

	return;

}
