
/* 1 "LANCEV2" */
/* $
     IR file generated by LANCE V2.0 (stcleanup) on
     Sunday, Jun 21, 2020 at 09:49:34
$ */

int main();

static char *lance_static_t3 = "%d ";

static char *lance_static_t7 = "%d\n";

int main()
{
 int n_3;
 int temp_4;
 int t8;
 int t2;
 int t4;
 int t5;


 /* 2 "/home/anushkini/Desktop/PD/plagtool/Test_lance/pd_7.c" */
 /* $ int n = 12345;$ */

	n_3 = 12345;

 /* 5 "/home/anushkini/Desktop/PD/plagtool/Test_lance/pd_7.c" */
 /* $ temp = n % 10;$ */

	t2 = n_3 % 10;
	temp_4 = t2;

 /* 6 "/home/anushkini/Desktop/PD/plagtool/Test_lance/pd_7.c" */
 /* $ printf("%d ",temp);$ */

	t4 = printf(lance_static_t3,temp_4);

 /* 7 "/home/anushkini/Desktop/PD/plagtool/Test_lance/pd_7.c" */
 /* $ n = n / 10;$ */

	t5 = n_3 / 10;
	n_3 = t5;

 /* 4 "/home/anushkini/Desktop/PD/plagtool/Test_lance/pd_7.c" */
 /* $ while(n >= 10) {$ */

 LL1:

 /* 9 "/home/anushkini/Desktop/PD/plagtool/Test_lance/pd_7.c" */
 /* $ printf("%d\n",temp);$ */

	t8 = printf(lance_static_t7,temp_4);

 /* 0 "???" */
 /* $ ???$ */

	return;

}
