
/* 1 "LANCEV2" */
/* $
     IR file generated by LANCE V2.0 (./myapp) on
     Saturday, Jun 20, 2020 at 21:55:50
$ */

int main();

static char *lance_static_t3 = "%d %d\n";

int main()
{
 int a_3;
 int b_4;
 int t1;
 int c_5;
 int t2;
 int d_6;
 int t4;


 /* 2 "/home/anushkini/Desktop/PD/plagtool/Test_lance/addSub-1.c" */
 /* $ int a = 10;$ */

	a_3 = 10;

 /* 3 "/home/anushkini/Desktop/PD/plagtool/Test_lance/addSub-1.c" */
 /* $ int b = 15;$ */

	b_4 = 15;

 /* 4 "/home/anushkini/Desktop/PD/plagtool/Test_lance/addSub-1.c" */
 /* $ int c = a + b;$ */

	t1 = a_3 + b_4;
	c_5 = t1;

 /* 5 "/home/anushkini/Desktop/PD/plagtool/Test_lance/addSub-1.c" */
 /* $ int d = a - b;$ */

	t2 = a_3 - b_4;
	d_6 = t2;

 /* 6 "/home/anushkini/Desktop/PD/plagtool/Test_lance/addSub-1.c" */
 /* $ printf("%d %d\n",c,d);$ */

	t4 = printf(lance_static_t3,c_5,d_6);

 /* 0 "???" */
 /* $ ???$ */

	return;

}
