
/* 1 "LANCEV2" */
/* $
     IR file generated by LANCE V2.0 (stcleanup) on
     Sunday, Jun 21, 2020 at 09:49:34
$ */

int add(int ,int );
int sub(int ,int );
int main();

static char *lance_static_t5 = "%d %d\n";

int add(int n1_2,int n2_3)
{
 int n3_5;
 int t1;


 /* 3 "/home/anushkini/Desktop/PD/plagtool/Test_lance/addSub_4.c" */
 /* $ n3 = n1 + n2;$ */

	t1 = n1_2 + n2_3;
	n3_5 = t1;

 /* 4 "/home/anushkini/Desktop/PD/plagtool/Test_lance/addSub_4.c" */
 /* $ return n3;$ */

	return n3_5;

}

int sub(int n1_6,int n2_7)
{
 int n3_9;
 int t2;


 /* 9 "/home/anushkini/Desktop/PD/plagtool/Test_lance/addSub_4.c" */
 /* $ n3 = n1 - n2;$ */

	t2 = n1_6 - n2_7;
	n3_9 = t2;

 /* 10 "/home/anushkini/Desktop/PD/plagtool/Test_lance/addSub_4.c" */
 /* $ return n3;$ */

	return n3_9;

}

int main()
{
 int n1_11;
 int n2_12;
 int t3;
 int t4;
 int t6;


 /* 14 "/home/anushkini/Desktop/PD/plagtool/Test_lance/addSub_4.c" */
 /* $ int n1 = 10;$ */

	n1_11 = 10;

 /* 15 "/home/anushkini/Desktop/PD/plagtool/Test_lance/addSub_4.c" */
 /* $ int n2 = 15;$ */

	n2_12 = 15;

 /* 16 "/home/anushkini/Desktop/PD/plagtool/Test_lance/addSub_4.c" */
 /* $ int n3 = add(n1,n2);$ */

	t3 = add(n1_11,n2_12);

 /* 17 "/home/anushkini/Desktop/PD/plagtool/Test_lance/addSub_4.c" */
 /* $ int n4 = sub(n1,n2);$ */

	t4 = sub(n1_11,n2_12);

 /* 18 "/home/anushkini/Desktop/PD/plagtool/Test_lance/addSub_4.c" */
 /* $ printf("%d %d\n",n1,n2);$ */

	t6 = printf(lance_static_t5,n1_11,n2_12);

 /* 0 "???" */
 /* $ ???$ */

	return;

}
