
/* 1 "LANCEV2" */
/* $
     IR file generated by LANCE V2.0 (./myapp) on
     Saturday, Jun 20, 2020 at 21:55:50
$ */

int main();

static char *lance_static_t6 = "Factorial of %d is %d";

int main()
{
 int res_3;
 int i_4;
 int num_5;
 int t1;
 int t2;
 int t3;
 int t4;
 int t5;
 int t7;


 /* 2 "/home/anushkini/Desktop/PD/plagtool/Test_lance/f-2.c" */
 /* $ { int res = 1;$ */

	res_3 = 1;

 /* 4 "/home/anushkini/Desktop/PD/plagtool/Test_lance/f-2.c" */
 /* $ int num = 5;$ */

	num_5 = 5;

 /* 5 "/home/anushkini/Desktop/PD/plagtool/Test_lance/f-2.c" */
 /* $ for(i=1;i<=num;i++) res*=i;$ */

	i_4 = 1;
	if (t5) goto LL1;

 LL3:
	t4 = res_3 * i_4;
	res_3 = t4;
 LL2:
	t2 = i_4;
	t3 = t2 + 1;
	i_4 = t3;
	if (t1) goto LL3;

 LL1:

 /* 6 "/home/anushkini/Desktop/PD/plagtool/Test_lance/f-2.c" */
 /* $ printf("Factorial of %d is %d", num, res);$ */

	t7 = printf(lance_static_t6,num_5,res_3);

 /* 7 "/home/anushkini/Desktop/PD/plagtool/Test_lance/f-2.c" */
 /* $ return 0;$ */

	return 0;

}
