
/* 1 "LANCEV2" */
/* $
     IR file generated by LANCE V2.0 (compile) on
     Saturday, Jun 20, 2020 at 21:55:50
$ */

int main();

static char *lance_static_t57 = "Factorial: %d\n";

int main()
{
 int fac_3[13];
 char *t1;
 int t2;
 char *t3;
 int *t4;
 char *t5;
 int t6;
 char *t7;
 int *t8;
 char *t9;
 int t10;
 char *t11;
 int *t12;
 char *t13;
 int t14;
 char *t15;
 int *t16;
 char *t17;
 int t18;
 char *t19;
 int *t20;
 char *t21;
 int t22;
 char *t23;
 int *t24;
 char *t25;
 int t26;
 char *t27;
 int *t28;
 char *t29;
 int t30;
 char *t31;
 int *t32;
 char *t33;
 int t34;
 char *t35;
 int *t36;
 char *t37;
 int t38;
 char *t39;
 int *t40;
 char *t41;
 int t42;
 char *t43;
 int *t44;
 char *t45;
 int t46;
 char *t47;
 int *t48;
 char *t49;
 int t50;
 char *t51;
 int *t52;
 int num_4;
 char *t53;
 int t54;
 char *t55;
 int *t56;
 int res_5;
 int t58;


 /* 3 "/home/anushkini/Desktop/PD/plagtool/Test_lance/f-3.c" */
 /* $ int fac[] = {1, 1, 2, 6, 24, 120, 720, 5040,  ...0$ */

	t3 = (char *)fac_3;
	t2 = 0 * 4;
	t1 = t3 + t2;
	t4 = (int *)t1;
	t7 = (char *)fac_3;
	t6 = 1 * 4;
	t5 = t7 + t6;
	t8 = (int *)t5;
	t11 = (char *)fac_3;
	t10 = 2 * 4;
	t9 = t11 + t10;
	t12 = (int *)t9;
	t15 = (char *)fac_3;
	t14 = 3 * 4;
	t13 = t15 + t14;
	t16 = (int *)t13;
	t19 = (char *)fac_3;
	t18 = 4 * 4;
	t17 = t19 + t18;
	t20 = (int *)t17;
	t23 = (char *)fac_3;
	t22 = 5 * 4;
	t21 = t23 + t22;
	t24 = (int *)t21;
	t27 = (char *)fac_3;
	t26 = 6 * 4;
	t25 = t27 + t26;
	t28 = (int *)t25;
	t31 = (char *)fac_3;
	t30 = 7 * 4;
	t29 = t31 + t30;
	t32 = (int *)t29;
	t35 = (char *)fac_3;
	t34 = 8 * 4;
	t33 = t35 + t34;
	t36 = (int *)t33;
	t39 = (char *)fac_3;
	t38 = 9 * 4;
	t37 = t39 + t38;
	t40 = (int *)t37;
	t43 = (char *)fac_3;
	t42 = 10 * 4;
	t41 = t43 + t42;
	t44 = (int *)t41;
	t47 = (char *)fac_3;
	t46 = 11 * 4;
	t45 = t47 + t46;
	t48 = (int *)t45;
	t51 = (char *)fac_3;
	t50 = 12 * 4;
	t49 = t51 + t50;
	t52 = (int *)t49;
	*t4 = 1;
	*t8 = 1;
	*t12 = 2;
	*t16 = 6;
	*t20 = 24;
	*t24 = 120;
	*t28 = 720;
	*t32 = 5040;
	*t36 = 40320;
	*t40 = 362880;
	*t44 = 3628800;
	*t48 = 39916800;
	*t52 = 479001600;

 /* 4 "/home/anushkini/Desktop/PD/plagtool/Test_lance/f-3.c" */
 /* $ int num = 5;$ */

	num_4 = 5;

 /* 5 "/home/anushkini/Desktop/PD/plagtool/Test_lance/f-3.c" */
 /* $ int res = fac[num];$ */

	t55 = (char *)fac_3;
	t54 = num_4 * 4;
	t53 = t55 + t54;
	t56 = (int *)t53;
	res_5 = *t56;

 /* 6 "/home/anushkini/Desktop/PD/plagtool/Test_lance/f-3.c" */
 /* $ printf("Factorial: %d\n",res);$ */

	t58 = printf(lance_static_t57,res_5);

 /* 0 "???" */
 /* $ ???$ */

	return;
}
