
/* 1 "LANCEV2" */
/* $
     IR file generated by LANCE V2.0 (stcleanup) on
     Sunday, Jun 21, 2020 at 09:49:34
$ */

int factorial(int );
int main();

static char *lance_static_t23 = "Factorial of %d is %d";

int factorial(int n_2)
{
 int t12;
 int t13;
 int t14;


 /* 4 "/home/anushkini/Desktop/PD/plagtool/Test_lance/f_2.c" */
 /* $ return 1;$ */

	return 1;


 /* 5 "/home/anushkini/Desktop/PD/plagtool/Test_lance/f_2.c" */
 /* $ for(a=0;a;a++){$ */

 LL2:

 /* 13 "/home/anushkini/Desktop/PD/plagtool/Test_lance/f_2.c" */
 /* $ return n * factorial(n-1);$ */

	t12 = n_2 - 1;
	t13 = factorial(t12);
	t14 = n_2 * t13;
	return t14;

}

int main()
{
 int num_12;
 int t22;
 int t24;
 int t25;


 /* 19 "/home/anushkini/Desktop/PD/plagtool/Test_lance/f_2.c" */
 /* $ int num = 5;$ */

	num_12 = 5;

 /* 20 "/home/anushkini/Desktop/PD/plagtool/Test_lance/f_2.c" */
 /* $ num = num;$ */

	num_12 = num_12;

 /* 24 "/home/anushkini/Desktop/PD/plagtool/Test_lance/f_2.c" */
 /* $ if(a ==1){$ */

	if (t22) goto LL5;

 LL5:

 /* 29 "/home/anushkini/Desktop/PD/plagtool/Test_lance/f_2.c" */
 /* $ printf("Factorial of %d is %d", num, factoria ...m$ */

	t24 = factorial(num_12);
	t25 = printf(lance_static_t23,num_12,t24);

 /* 30 "/home/anushkini/Desktop/PD/plagtool/Test_lance/f_2.c" */
 /* $ return 0;$ */

	return 0;

}
