
/* 1 "LANCEV2" */
/* $
     IR file generated by LANCE V2.0 (./myapp) on
     Saturday, Jun 20, 2020 at 21:55:50
$ */

int add(int ,int );
int sub(int ,int );
int main();

static char *lance_static_t5 = "%d %d\n";

int add(int a_2,int b_3)
{
 int c_5;
 int t1;


 /* 3 "/home/anushkini/Desktop/PD/plagtool/Test_lance/addSub.c" */
 /* $ c = a + b ;$ */

	t1 = a_2 + b_3;
	c_5 = t1;

 /* 4 "/home/anushkini/Desktop/PD/plagtool/Test_lance/addSub.c" */
 /* $ return c ;$ */

	return c_5;

}

int sub(int a_6,int b_7)
{
 int c_9;
 int t2;


 /* 9 "/home/anushkini/Desktop/PD/plagtool/Test_lance/addSub.c" */
 /* $ c = a - b ;$ */

	t2 = a_6 - b_7;
	c_9 = t2;

 /* 10 "/home/anushkini/Desktop/PD/plagtool/Test_lance/addSub.c" */
 /* $ return c ;$ */

	return c_9;

}

int main()
{
 int a_11;
 int b_12;
 int t3;
 int c_13;
 int t4;
 int d_14;
 int t6;


 /* 14 "/home/anushkini/Desktop/PD/plagtool/Test_lance/addSub.c" */
 /* $ int a = 10;$ */

	a_11 = 10;

 /* 15 "/home/anushkini/Desktop/PD/plagtool/Test_lance/addSub.c" */
 /* $ int b = 15;$ */

	b_12 = 15;

 /* 16 "/home/anushkini/Desktop/PD/plagtool/Test_lance/addSub.c" */
 /* $ int c = add(a,b);$ */

	t3 = add(a_11,b_12);
	c_13 = t3;

 /* 17 "/home/anushkini/Desktop/PD/plagtool/Test_lance/addSub.c" */
 /* $ int d = sub(a,b);$ */

	t4 = sub(a_11,b_12);
	d_14 = t4;

 /* 18 "/home/anushkini/Desktop/PD/plagtool/Test_lance/addSub.c" */
 /* $ printf("%d %d\n",c,d);$ */

	t6 = printf(lance_static_t5,c_13,d_14);

 /* 0 "???" */
 /* $ ???$ */

	return;

}
