
/* 1 "LANCEV2" */
/* $
     IR file generated by LANCE V2.0 (stcleanup) on
     Sunday, Jun 21, 2020 at 09:49:34
$ */

int main();

static char *lance_static_t9 = "The swapped numbers are %d and %d";

int main()
{
 int pq_3;
 int rs_4;
 int temp_5;
 int t10;


 /* 2 "/home/anushkini/Desktop/PD/plagtool/Test_lance/s_6.c" */
 /* $ int pq = 3;$ */

	pq_3 = 3;

 /* 3 "/home/anushkini/Desktop/PD/plagtool/Test_lance/s_6.c" */
 /* $ int rs = 5;$ */

	rs_4 = 5;

 /* 10 "/home/anushkini/Desktop/PD/plagtool/Test_lance/s_6.c" */
 /* $ while(a!=10){$ */

 LL1:

 /* 21 "/home/anushkini/Desktop/PD/plagtool/Test_lance/s_6.c" */
 /* $ temp = pq;$ */

	temp_5 = pq_3;

 /* 22 "/home/anushkini/Desktop/PD/plagtool/Test_lance/s_6.c" */
 /* $ pq = rs;$ */

	pq_3 = rs_4;

 /* 23 "/home/anushkini/Desktop/PD/plagtool/Test_lance/s_6.c" */
 /* $ rs = temp;$ */

	rs_4 = temp_5;

 /* 29 "/home/anushkini/Desktop/PD/plagtool/Test_lance/s_6.c" */
 /* $ printf("The swapped numbers are %d and %d",pq,rs);$ */

	t10 = printf(lance_static_t9,pq_3,rs_4);

 /* 0 "???" */
 /* $ ???$ */

	return;

}
