
/* 1 "LANCEV2" */
/* $
     IR file generated by LANCE V2.0 (./myapp) on
     Saturday, Jun 20, 2020 at 21:55:51
$ */

int main();

static char *lance_static_t1 = "Product: %d\n";

int main()
{
 int a_3;
 int b_4;
 int t2;
 int t3;


 /* 3 "/home/anushkini/Desktop/PD/plagtool/Test_lance/mul-2.c" */
 /* $ int a = 5;$ */

	a_3 = 5;

 /* 4 "/home/anushkini/Desktop/PD/plagtool/Test_lance/mul-2.c" */
 /* $ int b = 3;$ */

	b_4 = 3;

 /* 5 "/home/anushkini/Desktop/PD/plagtool/Test_lance/mul-2.c" */
 /* $ printf("Product: %d\n",a*b);$ */

	t2 = a_3 * b_4;
	t3 = printf(lance_static_t1,t2);

 /* 0 "???" */
 /* $ ???$ */

	return;

}
