
/* 1 "LANCEV2" */
/* $
     IR file generated by LANCE V2.0 (stcleanup) on
     Sunday, Jun 21, 2020 at 09:49:34
$ */

int mul(int ,int );
int main();

static char *lance_static_t2 = "Product: %d\n";

int main()
{
 int a_4;
 int b_5;
 int t1;
 int res_6;
 int t3;


 /* 3 "/home/anushkini/Desktop/PD/plagtool/Test_lance/mul_1.c" */
 /* $ int a = 5;$ */

	a_4 = 5;

 /* 4 "/home/anushkini/Desktop/PD/plagtool/Test_lance/mul_1.c" */
 /* $ int b = 3;$ */

	b_5 = 3;

 /* 5 "/home/anushkini/Desktop/PD/plagtool/Test_lance/mul_1.c" */
 /* $ int res = mul(a,b);$ */

	t1 = mul(a_4,b_5);
	res_6 = t1;

 /* 6 "/home/anushkini/Desktop/PD/plagtool/Test_lance/mul_1.c" */
 /* $ printf("Product: %d\n",res);$ */

	t3 = printf(lance_static_t2,res_6);

 /* 0 "???" */
 /* $ ???$ */

	return;

}

int mul(int a_8,int b_9)
{
 int res_11;
 int t8;
 int t7;


 /* 9 "/home/anushkini/Desktop/PD/plagtool/Test_lance/mul_1.c" */
 /* $ int res = 0, i;$ */

	res_11 = 0;

 /* 10 "/home/anushkini/Desktop/PD/plagtool/Test_lance/mul_1.c" */
 /* $ for(i = 0; i < b; i++) {$ */

	if (t8) goto LL1;

 LL3:

 /* 11 "/home/anushkini/Desktop/PD/plagtool/Test_lance/mul_1.c" */
 /* $ res += a;$ */

	t7 = res_11 + a_8;
	res_11 = t7;

 /* 10 "/home/anushkini/Desktop/PD/plagtool/Test_lance/mul_1.c" */
 /* $ for(i = 0; i < b; i++) {$ */

 LL1:

 /* 13 "/home/anushkini/Desktop/PD/plagtool/Test_lance/mul_1.c" */
 /* $ return res;$ */

	return res_11;

}
