
/* 1 "LANCEV2" */
/* $
     IR file generated by LANCE V2.0 (./myapp) on
     Saturday, Jun 20, 2020 at 21:55:51
$ */

int main();

static char *lance_static_t1 = "The swapped numbers are %d and %d";

int main()
{
 int a_3;
 int b_4;
 int t2;


 /* 2 "/home/anushkini/Desktop/PD/plagtool/Test_lance/s-3.c" */
 /* $ int a = 3;$ */

	a_3 = 3;

 /* 3 "/home/anushkini/Desktop/PD/plagtool/Test_lance/s-3.c" */
 /* $ int b = 5;$ */

	b_4 = 5;

 /* 5 "/home/anushkini/Desktop/PD/plagtool/Test_lance/s-3.c" */
 /* $ printf("The swapped numbers are %d and %d",b, a);$ */

	t2 = printf(lance_static_t1,b_4,a_3);

 /* 0 "???" */
 /* $ ???$ */

	return;

}
