
/* 1 "LANCEV2" */
/* $
     IR file generated by LANCE V2.0 (./myapp) on
     Saturday, Jun 20, 2020 at 21:55:51
$ */

int main();

static char *lance_static_t1 = "The swapped numbers are %d and %d";

int main()
{
 int a_3;
 int b_4;
 int temp_5;
 int t2;


 /* 2 "/home/anushkini/Desktop/PD/plagtool/Test_lance/s.c" */
 /* $ int a = 3;$ */

	a_3 = 3;

 /* 3 "/home/anushkini/Desktop/PD/plagtool/Test_lance/s.c" */
 /* $ int b = 5;$ */

	b_4 = 5;

 /* 6 "/home/anushkini/Desktop/PD/plagtool/Test_lance/s.c" */
 /* $ temp = a;$ */

	temp_5 = a_3;

 /* 7 "/home/anushkini/Desktop/PD/plagtool/Test_lance/s.c" */
 /* $ a = b;$ */

	a_3 = b_4;

 /* 8 "/home/anushkini/Desktop/PD/plagtool/Test_lance/s.c" */
 /* $ b = temp;$ */

	b_4 = temp_5;

 /* 10 "/home/anushkini/Desktop/PD/plagtool/Test_lance/s.c" */
 /* $ printf("The swapped numbers are %d and %d",a,b);$ */

	t2 = printf(lance_static_t1,a_3,b_4);

 /* 0 "???" */
 /* $ ???$ */

	return;

}
