
/* 1 "LANCEV2" */
/* $
     IR file generated by LANCE V2.0 (stcleanup) on
     Sunday, Jun 21, 2020 at 09:49:34
$ */

void swap(int *,int *);
int main();

static char *lance_static_t18 = "The swapped numbers are %d and %d";

void swap(int *pq_2,int *rs_3)
{
 int temp_5;
 int a_6;
 int b_7;
 int c_8;
 int t1;
 int t14;
 int t2;
 int t3;
 int t4;
 int t5;
 int t6;
 int t7;
 int t8;
 int t9;
 int t10;
 int t11;
 int t12;
 int t13;


 /* 5 "/home/anushkini/Desktop/PD/plagtool/Test_lance/s_3.c" */
 /* $ a= 10;$ */

	a_6 = 10;

 /* 6 "/home/anushkini/Desktop/PD/plagtool/Test_lance/s_3.c" */
 /* $ b= 20;$ */

	b_7 = 20;

 /* 7 "/home/anushkini/Desktop/PD/plagtool/Test_lance/s_3.c" */
 /* $ c = 30;$ */

	c_8 = 30;

 /* 9 "/home/anushkini/Desktop/PD/plagtool/Test_lance/s_3.c" */
 /* $ if(a!=10){$ */

	t1 = a_6 != 10;
	t14 = !t1;
	if (t14) goto LL1;


 /* 10 "/home/anushkini/Desktop/PD/plagtool/Test_lance/s_3.c" */
 /* $ a = b;$ */

	a_6 = b_7;

 /* 11 "/home/anushkini/Desktop/PD/plagtool/Test_lance/s_3.c" */
 /* $ b = c;$ */

	b_7 = c_8;

 /* 12 "/home/anushkini/Desktop/PD/plagtool/Test_lance/s_3.c" */
 /* $ c = a;$ */

	c_8 = a_6;

 /* 13 "/home/anushkini/Desktop/PD/plagtool/Test_lance/s_3.c" */
 /* $ a++;$ */

	t2 = a_6;
	t3 = t2 + 1;
	a_6 = t3;

 /* 14 "/home/anushkini/Desktop/PD/plagtool/Test_lance/s_3.c" */
 /* $ b++;$ */

	t4 = b_7;
	t5 = t4 + 1;
	b_7 = t5;

 /* 15 "/home/anushkini/Desktop/PD/plagtool/Test_lance/s_3.c" */
 /* $ c++;$ */

	t6 = c_8;
	t7 = t6 + 1;
	c_8 = t7;

 /* 16 "/home/anushkini/Desktop/PD/plagtool/Test_lance/s_3.c" */
 /* $ a--;$ */

	t8 = a_6;
	t9 = t8 - 1;
	a_6 = t9;

 /* 17 "/home/anushkini/Desktop/PD/plagtool/Test_lance/s_3.c" */
 /* $ b--;$ */

	t10 = b_7;
	t11 = t10 - 1;
	b_7 = t11;

 /* 18 "/home/anushkini/Desktop/PD/plagtool/Test_lance/s_3.c" */
 /* $ c--;$ */

	t12 = c_8;
	t13 = t12 - 1;
	c_8 = t13;

 /* 9 "/home/anushkini/Desktop/PD/plagtool/Test_lance/s_3.c" */
 /* $ if(a!=10){$ */

 LL1:

 /* 20 "/home/anushkini/Desktop/PD/plagtool/Test_lance/s_3.c" */
 /* $ temp = *pq;$ */

	temp_5 = *pq_2;

 /* 21 "/home/anushkini/Desktop/PD/plagtool/Test_lance/s_3.c" */
 /* $ *pq = *rs;$ */

	*pq_2 = *rs_3;

 /* 22 "/home/anushkini/Desktop/PD/plagtool/Test_lance/s_3.c" */
 /* $ *rs = temp;$ */

	*rs_3 = temp_5;

 /* 23 "/home/anushkini/Desktop/PD/plagtool/Test_lance/s_3.c" */
 /* $ a= 10;$ */

	a_6 = 10;

 /* 24 "/home/anushkini/Desktop/PD/plagtool/Test_lance/s_3.c" */
 /* $ b= 20;$ */

	b_7 = 20;

 /* 25 "/home/anushkini/Desktop/PD/plagtool/Test_lance/s_3.c" */
 /* $ c = 30;$ */

	c_8 = 30;

 /* 0 "???" */
 /* $ ???$ */

	return;

}

int main()
{
 int pq_10;
 int rs_11;
 int a_12;
 int b_13;
 int c_14;
 int *t15;
 int *t16;
 int t19;
 int t1;


 /* 29 "/home/anushkini/Desktop/PD/plagtool/Test_lance/s_3.c" */
 /* $ int pq = 3;$ */

	pq_10 = 3;

 /* 30 "/home/anushkini/Desktop/PD/plagtool/Test_lance/s_3.c" */
 /* $ int rs = 5;$ */

	rs_11 = 5;

 /* 33 "/home/anushkini/Desktop/PD/plagtool/Test_lance/s_3.c" */
 /* $ a= 10;$ */

	a_12 = 10;

 /* 34 "/home/anushkini/Desktop/PD/plagtool/Test_lance/s_3.c" */
 /* $ b= 20;$ */

	b_13 = 20;

 /* 35 "/home/anushkini/Desktop/PD/plagtool/Test_lance/s_3.c" */
 /* $ c = 30;$ */

	c_14 = 30;

 /* 36 "/home/anushkini/Desktop/PD/plagtool/Test_lance/s_3.c" */
 /* $ swap(&pq, &rs);$ */

	t15 = &pq_10;
	t16 = &rs_11;
	swap(t15,t16);

 /* 37 "/home/anushkini/Desktop/PD/plagtool/Test_lance/s_3.c" */
 /* $ a= 10;$ */

	a_12 = 10;

 /* 38 "/home/anushkini/Desktop/PD/plagtool/Test_lance/s_3.c" */
 /* $ b= 20;$ */

	b_13 = 20;

 /* 39 "/home/anushkini/Desktop/PD/plagtool/Test_lance/s_3.c" */
 /* $ c = 30;$ */

	c_14 = 30;

 /* 40 "/home/anushkini/Desktop/PD/plagtool/Test_lance/s_3.c" */
 /* $ printf("The swapped numbers are %d and %d",pq,rs);$ */

	t19 = printf(lance_static_t18,pq_10,rs_11);

 /* 0 "???" */
 /* $ ???$ */

	return;

}
