
/* 1 "LANCEV2" */
/* $
     IR file generated by LANCE V2.0 (./myapp) on
     Saturday, Jun 20, 2020 at 21:55:51
$ */

int main();

static char *lance_static_t1 = "The swapped numbers are %d and %d";

int main()
{
 int first_3;
 int secons_4;
 int third_5;
 int t2;


 /* 2 "/home/anushkini/Desktop/PD/plagtool/Test_lance/s_5.c" */
 /* $ int first = 3;$ */

	first_3 = 3;

 /* 3 "/home/anushkini/Desktop/PD/plagtool/Test_lance/s_5.c" */
 /* $ int secons = 5;$ */

	secons_4 = 5;

 /* 6 "/home/anushkini/Desktop/PD/plagtool/Test_lance/s_5.c" */
 /* $ third = first;$ */

	third_5 = first_3;

 /* 7 "/home/anushkini/Desktop/PD/plagtool/Test_lance/s_5.c" */
 /* $ first = secons;$ */

	first_3 = secons_4;

 /* 8 "/home/anushkini/Desktop/PD/plagtool/Test_lance/s_5.c" */
 /* $ secons = third;$ */

	secons_4 = third_5;

 /* 10 "/home/anushkini/Desktop/PD/plagtool/Test_lance/s_5.c" */
 /* $ printf("The swapped numbers are %d and %d",fi ...s$ */

	t2 = printf(lance_static_t1,first_3,secons_4);

 /* 0 "???" */
 /* $ ???$ */

	return;

}
