
/* 1 "LANCEV2" */
/* $
     IR file generated by LANCE V2.0 (./myapp) on
     Saturday, Jun 20, 2020 at 21:55:51
$ */

int main();

static char *lance_static_t1 = "The swapped numbers are %d and %d";

int main()
{
 int a_3;
 int b_4;
 int temp_5;
 int t2;


 /* 2 "/home/anushkini/Desktop/PD/plagtool/Test_lance/s_7.c" */
 /* $ int a = 3, b= 5, temp;temp = a;a = b;b = temp ...n$ */

	a_3 = 3;
	b_4 = 5;
	temp_5 = a_3;
	a_3 = b_4;
	b_4 = temp_5;
	t2 = printf(lance_static_t1,a_3,b_4);

 /* 0 "???" */
 /* $ ???$ */

	return;

}
