
/* 1 "LANCEV2" */
/* $
     IR file generated by LANCE V2.0 (./myapp) on
     Saturday, Jun 20, 2020 at 21:55:50
$ */

int factorial(int );
int main();

static char *lance_static_t6 = "Factorial of %d is %d";

int factorial(int n_2)
{
 int res_ult_4;
 int index_5;
 int t1;
 int t2;
 int t3;
 int t4;
 int t5;


 /* 3 "/home/anushkini/Desktop/PD/plagtool/Test_lance/f_1.c" */
 /* $ int res_ult = 1, index;$ */

	res_ult_4 = 1;

 /* 4 "/home/anushkini/Desktop/PD/plagtool/Test_lance/f_1.c" */
 /* $ for (index = 2; index <= n; index++)$ */

	index_5 = 2;
	if (t5) goto LL1;

 LL3:

 /* 5 "/home/anushkini/Desktop/PD/plagtool/Test_lance/f_1.c" */
 /* $ res_ult *= index;$ */

	t4 = res_ult_4 * index_5;
	res_ult_4 = t4;

 /* 4 "/home/anushkini/Desktop/PD/plagtool/Test_lance/f_1.c" */
 /* $ for (index = 2; index <= n; index++)$ */

 LL2:
	t2 = index_5;
	t3 = t2 + 1;
	index_5 = t3;
	if (t1) goto LL3;

 LL1:

 /* 6 "/home/anushkini/Desktop/PD/plagtool/Test_lance/f_1.c" */
 /* $ return res_ult;$ */

	return res_ult_4;

}

int main()
{
 int numero_7;
 int t7;
 int t8;


 /* 11 "/home/anushkini/Desktop/PD/plagtool/Test_lance/f_1.c" */
 /* $ int numero = 5;$ */

	numero_7 = 5;

 /* 13 "/home/anushkini/Desktop/PD/plagtool/Test_lance/f_1.c" */
 /* $ printf("Factorial of %d is %d", numero, facto ...($ */

	t7 = factorial(numero_7);
	t8 = printf(lance_static_t6,numero_7,t7);

 /* 14 "/home/anushkini/Desktop/PD/plagtool/Test_lance/f_1.c" */
 /* $ return 0;$ */

	return 0;

}
