
/* 1 "LANCEV2" */
/* $
     IR file generated by LANCE V2.0 (stcleanup) on
     Sunday, Jun 21, 2020 at 09:49:34
$ */

int factorial(int );
int main();

static char *lance_static_t7 = "Factorial of %d is %d";

int factorial(int n_2)
{
 int result_4;
 int i_5;
 int t1;
 int t2;
 int t3;
 int t4;
 int t5;


 /* 3 "/home/anushkini/Desktop/PD/plagtool/Test_lance/f_6.c" */
 /* $ int result = 1, i;$ */

	result_4 = 1;

 /* 5 "/home/anushkini/Desktop/PD/plagtool/Test_lance/f_6.c" */
 /* $ for (i = 2; i <= n; i++)$ */

	i_5 = 2;
	if (t5) goto LL1;

 LL3:

 /* 6 "/home/anushkini/Desktop/PD/plagtool/Test_lance/f_6.c" */
 /* $ result *= i;$ */

	t4 = result_4 * i_5;
	result_4 = t4;

 /* 5 "/home/anushkini/Desktop/PD/plagtool/Test_lance/f_6.c" */
 /* $ for (i = 2; i <= n; i++)$ */

 LL2:
	t2 = i_5;
	t3 = t2 + 1;
	i_5 = t3;
	if (t1) goto LL3;

 LL1:

 /* 7 "/home/anushkini/Desktop/PD/plagtool/Test_lance/f_6.c" */
 /* $ return result;$ */

	return result_4;

}

int main()
{
 int number_10;
 int t8;
 int t9;


 /* 12 "/home/anushkini/Desktop/PD/plagtool/Test_lance/f_6.c" */
 /* $ int number = 5;$ */

	number_10 = 5;

 /* 14 "/home/anushkini/Desktop/PD/plagtool/Test_lance/f_6.c" */
 /* $ while(a){$ */

 LL4:

 /* 23 "/home/anushkini/Desktop/PD/plagtool/Test_lance/f_6.c" */
 /* $ printf("Factorial of %d is %d", number, facto ...($ */

	t8 = factorial(number_10);
	t9 = printf(lance_static_t7,number_10,t8);

 /* 0 "???" */
 /* $ ???$ */

	return;

}
