
/* 1 "LANCEV2" */
/* $
     IR file generated by LANCE V2.0 (stcleanup) on
     Sunday, Jun 21, 2020 at 09:49:34
$ */

int print_digits(int );
int main();

static char *lance_static_t2 = "%d\n";

static char *lance_static_t6 = "%d ";

int main()
{
 int n_5;
 int t1;
 int l_6;
 int t3;


 /* 4 "/home/anushkini/Desktop/PD/plagtool/Test_lance/pd_5.c" */
 /* $ int n = 12345;$ */

	n_5 = 12345;

 /* 5 "/home/anushkini/Desktop/PD/plagtool/Test_lance/pd_5.c" */
 /* $ int l = print_digits(n);$ */

	t1 = print_digits(n_5);
	l_6 = t1;

 /* 6 "/home/anushkini/Desktop/PD/plagtool/Test_lance/pd_5.c" */
 /* $ printf("%d\n",l);$ */

	t3 = printf(lance_static_t2,l_6);

 /* 0 "???" */
 /* $ ???$ */

	return;

}

int print_digits(int n_8)
{
 int temp_10;
 int t5;
 int t7;
 int t8;


 /* 13 "/home/anushkini/Desktop/PD/plagtool/Test_lance/pd_5.c" */
 /* $ temp = n % 10;$ */

	t5 = n_8 % 10;
	temp_10 = t5;

 /* 14 "/home/anushkini/Desktop/PD/plagtool/Test_lance/pd_5.c" */
 /* $ printf("%d ",temp);$ */

	t7 = printf(lance_static_t6,temp_10);

 /* 15 "/home/anushkini/Desktop/PD/plagtool/Test_lance/pd_5.c" */
 /* $ n = n / 10;$ */

	t8 = n_8 / 10;
	n_8 = t8;

 /* 12 "/home/anushkini/Desktop/PD/plagtool/Test_lance/pd_5.c" */
 /* $ while(n >= 10) {$ */

 LL1:

 /* 17 "/home/anushkini/Desktop/PD/plagtool/Test_lance/pd_5.c" */
 /* $ return temp;$ */

	return temp_10;

}
