
/* 1 "LANCEV2" */
/* $
     IR file generated by LANCE V2.0 (./myapp) on
     Saturday, Jun 20, 2020 at 21:55:51
$ */

int mul(int ,int );
int main();

static char *lance_static_t3 = "Product: %d\n";

int mul(int a_2,int b_3)
{
 int t1;


 /* 2 "/home/anushkini/Desktop/PD/plagtool/Test_lance/mul-1.c" */
 /* $ return a*b;$ */

	t1 = a_2 * b_3;
	return t1;

}

int main()
{
 int a_6;
 int b_7;
 int t2;
 int res_8;
 int t4;


 /* 6 "/home/anushkini/Desktop/PD/plagtool/Test_lance/mul-1.c" */
 /* $ int a = 5;$ */

	a_6 = 5;

 /* 7 "/home/anushkini/Desktop/PD/plagtool/Test_lance/mul-1.c" */
 /* $ int b = 3;$ */

	b_7 = 3;

 /* 8 "/home/anushkini/Desktop/PD/plagtool/Test_lance/mul-1.c" */
 /* $ int res = mul(a,b);$ */

	t2 = mul(a_6,b_7);
	res_8 = t2;

 /* 9 "/home/anushkini/Desktop/PD/plagtool/Test_lance/mul-1.c" */
 /* $ printf("Product: %d\n",res);$ */

	t4 = printf(lance_static_t3,res_8);

 /* 0 "???" */
 /* $ ???$ */

	return;

}
